interface CLiente {
  id: number;
  nome: string;
  endereco: string;
  num: string;
  bairro: string;
  mun: string;
  uf: string;
  codf: string;
  ie_rg: string;
  fone: string;
  fonc: string;
  cep: number;
  fax: number;
  enc: string;
  bac: string;
  muc: string;
  ufc: string;
  cepc: string;
  cre: number;
  deb: number;
  duo: Date;
  pem: string;
  neg: Date;
  valor: string;
  datuf: Date;
  creb: string;
  vencimento: string;
  limite: string;
  tipcli: string;
  email: string;
  cmun: string;
  logradouro: string;
  compl_logr: string;
  fimdemes: number;
  datafimd: Date;
  obs_vend: string;
  obs_fifa: string;
  pagament: string;
  impfat: Boolean;
  gerfat: Boolean;
  mailfatu: string;
  semboleto: string;
}

export default CLiente;